# Konfigurasi Khusus Frontend (React Vite)
# Taruh file ini di ROOT (sejajar dengan package.json)

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.build]
cmds = ["npm install", "npm run build"]

[start]
cmd = "npx serve -s dist -l $PORT"