# Konfigurasi Khusus Frontend (React Vite)
# Taruh file ini di ROOT (sejajar dengan package.json)

[phases.setup]
# Cukup panggil "nodejs", npm otomatis ikut terinstall
nixPkgs = ["nodejs"]

[phases.build]
cmds = ["npm install", "npm run build"]

[start]
cmd = "npx serve -s dist -l $PORT"